# Generated by Django 5.2.5 on 2025-08-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='group',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='name',
        ),
        migrations.AddField(
            model_name='standard',
            name='code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='level',
            field=models.CharField(choices=[('IGCSE', 'IGCSE'), ('AS', 'AS Level'), ('A2', 'A Level')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
