# Generated by Django 5.2.5 on 2025-08-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology_app', '0002_rename_group_standard_unit_remove_standard_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_number']},
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
