# Generated by Django 5.2.5 on 2025-08-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology_app', '0003_alter_question_options_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_file_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
