# Generated by Django 5.2.5 on 2025-08-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology_app', '0004_test_test_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
