# Generated by Django 5.2.5 on 2025-08-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology_app', '0005_test_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['level', 'chapter_order', 'unit_order', 'code']},
        ),
        migrations.AddField(
            model_name='standard',
            name='chapter',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='chapter_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standard',
            name='unit_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='standard',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together={('level', 'code')},
        ),
    ]
